name: PHP CodeSniffer

on:
  push:
    branches:
      - master

jobs:
  phpcs:
    name: PHP Code sniffer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 3.7.2
        extensions: mbstring, zip

    - name: Install Composer dependencies
    - run: composer install --pref-dist --no-interaction
    - name: Run PHP code Sniffer
    - run: vendor/bin/phpcs src --standars=PSR1,PSR2